// [EN] This file defines the core data structures and types used throughout the application's analysis logic.
// [IT] Questo file definisce le strutture dati e i tipi principali usati nella logica di analisi dell'applicazione.

// --- USER INPUT ---
// [EN] Represents the hardware specifications provided by the user.
// [IT] Rappresenta le specifiche hardware fornite dall'utente.
export interface UserHardware {
	gpu: string;
	gpuFamily?: 'rtx-40' | 'rtx-30' | 'rtx-20' | 'amd-rx-7000' | 'generic';
	vram: number;
	ram: number;
	storage: 'hdd' | 'ssd' | 'nvme';
}

// --- DATABASE BUILDING BLOCKS ---
// [EN] Defines specific GPU requirements for certain components or quantizations.
// [IT] Definisce requisiti GPU specifici per certi componenti o quantizzazioni.
export interface GpuRequirements {
	supportedFamilies: UserHardware['gpuFamily'][];
	isSoftwareFallback: boolean;
	note?: string;
}

/**
 * [EN] Represents a possible precision/quantization format.
 * [IT] Rappresenta un possibile formato di precisione/quantizzazione.
 */
export interface Quantization {
	id:
		| 'fp16'
		| 'fp8'
		| 'int8'
		| 'fp4'
		| 'gguf-q2_k'
		| 'gguf-q3_k_m'
		| 'gguf-q4_0'
		| 'gguf-q4_k_m'
		| 'gguf-q5_0'
		| 'gguf-q5_k_m'
		| 'gguf-q6_k'
		| 'gguf-q8_0';
	name: string;
	vramMultiplier: number;
	ramMultiplier: number;
	notes: string[];
	gpuRequirements?: GpuRequirements;
}

/**
 * [EN] Represents a Text Encoder model.
 * [IT] Rappresenta un modello di Text Encoder.
 */
export interface TextEncoder {
	id: 'clip-l' | 'clip-g' | 't5-xxl';
	name: string;
	baseVramCost: number;
	baseRamCost: number;
	notes: string[];
}

/**
 * [EN] Represents a base model (e.g., a U-Net for image generation).
 * [IT] Rappresenta un modello base (es. una U-Net per la generazione di immagini).
 */
export interface BaseModel {
	id: 'sd-1.5' | 'sdxl' | 'flux1';
	name: 'Stable Diffusion 1.5' | 'Stable Diffusion XL' | 'FLUX.1';
	type: 'Image Generation' | 'Video Generation' | 'Music Generation' | 'LLM';
	baseVramCost: number;
	compatibleTextEncoders: TextEncoder['id'][];
	compatibleQuantizations: Quantization['id'][];
	gpuRequirements?: GpuRequirements;
}

// --- SYSTEM OUTPUT ---
// [EN] A complete "recipe" generated by combining a base model, quantization, and encoders.
// [IT] Una "ricetta" completa generata combinando un modello base, una quantizzazione e degli encoder.
export interface GeneratedRecipe {
	id: string;
	name: string;
	type: BaseModel['type'];
	baseModel: BaseModel;
	quantization: Quantization;
	textEncoders: TextEncoder[];
	totalVramCost: number;
	totalRamCost: number;
	setupNotes: string[];
}

// [EN] The compatibility level of a recipe with the user's hardware.
// [IT] Il livello di compatibilità di una ricetta con l'hardware dell'utente.
export type CompatibilityLevel = 'Optimal' | 'Good' | 'Poor' | 'Not Recommended';

// [EN] The final analysis result for a single recipe, including compatibility and performance notes.
// [IT] Il risultato finale dell'analisi per una singola ricetta, incluse note di compatibilità e performance.
export interface AnalysisResult {
	recipe: GeneratedRecipe;
	compatibility: CompatibilityLevel;
	performanceNotes: string[];
}